In [1]:
import pandas as pd
import numpy as np

In [3]:
#read csv files in data
train = pd.read_csv('data/train.csv')
test= pd.read_csv('data/test.csv')

In [10]:
#only show rows that have null values
train[train.isnull().any(axis=1)]
test[test.isnull().any(axis=1)]

Empty DataFrame
Columns: [row ID, full_sq, life_sq, floor, product_type, sub_area, area_m, raion_popul, green_zone_part, indust_part, children_preschool, preschool_education_centers_raion, children_school, school_education_centers_raion, school_education_centers_top_20_raion, healthcare_centers_raion, university_top_20_raion, sport_objects_raion, additional_education_raion, culture_objects_top_25, culture_objects_top_25_raion, shopping_centers_raion, office_raion, thermal_power_plant_raion, incineration_raion, oil_chemistry_raion, radiation_raion, railroad_terminal_raion, big_market_raion, nuclear_reactor_raion, detention_facility_raion, full_all, male_f, female_f, young_all, young_male, young_female, work_all, work_male, work_female, ekder_all, ekder_male, ekder_female, 0_6_all, 0_6_male, 0_6_female, 7_14_all, 7_14_male, 7_14_female, 0_17_all, 0_17_male, 0_17_female, 16_29_all, 16_29_male, 16_29_female, 0_13_all, 0_13_male, 0_13_female, raion_build_count_with_material_info, build_count_block, build_count_wood, build_count_frame, build_count_brick, build_count_monolith, build_count_panel, build_count_foam, build_count_slag, build_count_mix, raion_build_count_with_builddate_info, build_count_before_1920, build_count_1921-1945, build_count_1946-1970, build_count_1971-1995, build_count_after_1995, ID_metro, metro_min_avto, metro_km_avto, metro_min_walk, metro_km_walk, kindergarten_km, school_km, park_km, green_zone_km, industrial_km, water_treatment_km, cemetery_km, incineration_km, railroad_station_walk_km, railroad_station_walk_min, ID_railroad_station_walk, railroad_station_avto_km, railroad_station_avto_min, ID_railroad_station_avto, public_transport_station_km, public_transport_station_min_walk, water_km, water_1line, mkad_km, ttk_km, sadovoe_km, ...]
Index: []

[0 rows x 272 columns]

In [14]:
#only show train that has dtype=object
train.select_dtypes(include=['object']).columns

Index(['product_type', 'sub_area', 'culture_objects_top_25',
       'thermal_power_plant_raion', 'incineration_raion',
       'oil_chemistry_raion', 'radiation_raion', 'railroad_terminal_raion',
       'big_market_raion', 'nuclear_reactor_raion', 'detention_facility_raion',
       'water_1line', 'big_road1_1line', 'railroad_1line', 'ecology'],
      dtype='object')

In [19]:
#convert data types where coluhmns have values yes and no to 1 and 0
train = train.replace({'yes': 1, 'no': 0})
test = test.replace({'yes': 1, 'no': 0})

In [24]:
train[train['oil_chemistry_raion']==0]

,full_sq,life_sq,floor,product_type,sub_area,area_m,raion_popul,green_zone_part,indust_part,children_preschool,...,cafe_count_5000_price_2500,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000,price_doc
0,43.0,27.0,4.0,Investment,Bibirevo,6.407578e+06,155572.0,0.189727,0.000070,9576.0,...,9.0,4.0,0.0,13.0,22.0,1.0,0.0,52.0,4.0,5850000.0
1,34.0,19.0,3.0,Investment,Nagatinskij Zaton,9.589337e+06,115352.0,0.372602,0.049637,6880.0,...,15.0,3.0,0.0,15.0,29.0,1.0,10.0,66.0,14.0,6000000.0
2,43.0,29.0,2.0,Investment,Tekstil'shhiki,4.808270e+06,101708.0,0.112560,0.118537,5879.0,...,10.0,3.0,0.0,11.0,27.0,0.0,4.0,67.0,10.0,5700000.0
3,77.0,77.0,4.0,Investment,Basmannoe,8.398461e+06,108171.0,0.015234,0.037316,5706.0,...,319.0,108.0,17.0,135.0,236.0,2.0,91.0,195.0,14.0,16331452.0
4,67.0,46.0,14.0,Investment,Nizhegorodskoe,7.506452e+06,43795.0,0.007670,0.486246,2418.0,...,62.0,14.0,1.0,53.0,78.0,1.0,20.0,113.0,17.0,9100000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181502,48.0,33.0,3.0,Investment,Poselenie Mihajlovo-Jarcevskoe,6.455617e+07,4949.0,0.586175,0.005819,346.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,3480000.0
181503,48.0,33.0,3.0,Investment,Poselenie Mihajlovo-Jarcevskoe,6.455617e+07,4949.0,0.586175,0.005819,346.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,3480000.0
181504,48.0,33.0,3.0,Investment,Poselenie Mihajlovo-Jarcevskoe,6.455617e+07,4949.0,0.586175,0.005819,346.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,3480000.0
181505,48.0,33.0,3.0,Investment,Poselenie Mihajlovo-Jarcevskoe,6.455617e+07,4949.0,0.586175,0.005819,346.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,3480000.0
181506,48.0,33.0,3.0,Investment,Poselenie Mihajlovo-Jarcevskoe,6.455617e+07,4949.0,0.586175,0.005819,346.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,3480000.0

In [25]:
#make surre all yes and no are covnerted
train.select_dtypes(include=['object']).columns

Index(['product_type', 'sub_area', 'ecology'], dtype='object')

In [26]:
test.select_dtypes(include=['object']).columns

Index(['product_type', 'sub_area', 'ecology'], dtype='object')

In [36]:
#show unique values in train for object columns
for col in train.select_dtypes(include=['object']).columns:
    print(col, ':', train[col].unique(), 'labels')

In [29]:
# Import the necessary libraries
from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
lbl = LabelEncoder()

# Fit the label encoder on the combined data of train and test datasets
lbl.fit(list(train['ecology'].values) + list(test['ecology'].values))

# Convert the 'ecology' column in the train dataset
train['ecology'] = lbl.transform(list(train['ecology'].values))

# Convert the 'ecology' column in the test dataset
test['ecology'] = lbl.transform(list(test['ecology'].values))

In [30]:
#do one hot encoding for sub_area such that there is a m-1 columns
#where m is the number of unique values in sub_area
# do one hot encoding for sub_area such that there is a m-1 columns
# where m is the number of unique values in sub_area
train = pd.get_dummies(train, columns=['sub_area'], drop_first=True)
test = pd.get_dummies(test, columns=['sub_area'], drop_first=True)

In [31]:
#do label encoding for prodcut type as well
lbl.fit(list(train['product_type'].values) + list(test['product_type'].values))
train['product_type'] = lbl.transform(list(train['product_type'].values))
test['product_type'] = lbl.transform(list(test['product_type'].values))

In [32]:
test.select_dtypes(include=['object']).columns
train.select_dtypes(include=['object']).columns

Index([], dtype='object')

In [34]:
train

,full_sq,life_sq,floor,product_type,area_m,raion_popul,green_zone_part,indust_part,children_preschool,preschool_education_centers_raion,...,sub_area_uJzhnoe Tushino,sub_area_uJzhnoportovoe,sub_area_uKncevo,sub_area_uKrkino,sub_area_uKz'minki,sub_area_vIanovskoe,sub_area_vSiblovo,sub_area_vTerskoe,sub_area_yVhino-Zhulebino,sub_area_zImajlovo
0,43.0,27.0,4.0,0,6.407578e+06,155572.0,0.189727,0.000070,9576.0,5.0,...,0,0,0,0,0,0,0,0,0,0
1,34.0,19.0,3.0,0,9.589337e+06,115352.0,0.372602,0.049637,6880.0,5.0,...,0,0,0,0,0,0,0,0,0,0
2,43.0,29.0,2.0,0,4.808270e+06,101708.0,0.112560,0.118537,5879.0,4.0,...,0,0,0,0,0,0,0,0,0,0
3,77.0,77.0,4.0,0,8.398461e+06,108171.0,0.015234,0.037316,5706.0,7.0,...,0,0,0,0,0,0,0,0,0,0
4,67.0,46.0,14.0,0,7.506452e+06,43795.0,0.007670,0.486246,2418.0,2.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181502,48.0,33.0,3.0,0,6.455617e+07,4949.0,0.586175,0.005819,346.0,0.0,...,0,0,0,0,0,0,0,0,0,0
181503,48.0,33.0,3.0,0,6.455617e+07,4949.0,0.586175,0.005819,346.0,0.0,...,0,0,0,0,0,0,0,0,0,0
181504,48.0,33.0,3.0,0,6.455617e+07,4949.0,0.586175,0.005819,346.0,0.0,...,0,0,0,0,0,0,0,0,0,0
181505,48.0,33.0,3.0,0,6.455617e+07,4949.0,0.586175,0.005819,346.0,0.0,...,0,0,0,0,0,0,0,0,0,0
181506,48.0,33.0,3.0,0,6.455617e+07,4949.0,0.586175,0.005819,346.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [73]:
import statsmodels.api as sm

In [40]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [41]:
X = train.drop(columns=['price_doc'])
y = train[['price_doc']]

In [78]:
from sklearn.feature_selection import SequentialFeatureSelector

In [ ]:
ols_reg = LinearRegression()
sfs = SequentialFeatureSelector(ols_reg, direction='forward',n_features_to_select=1000)
sfs.fit(X, y)
print(sfs.get_feature_names_out())

In [ ]:
import matplotlib.pyplot as plt

# Get feature importance scores
feature_importance = cb.get_feature_importance()

# Create a dataframe with feature importance scores
df_feature_importance = pd.DataFrame({'Feature': X_train.columns, 'Importance': feature_importance})

# Sort the dataframe by importance score
df_feature_importance = df_feature_importance.sort_values(by='Importance', ascending=False)

# Plot the feature importance scores as a bar plot
plt.figure(figsize=(10, 6))
plt.bar(df_feature_importance['Feature'], df_feature_importance['Importance'])
plt.xticks(rotation=90)
plt.xlabel('Feature')
plt.ylabel('Importance Score')
plt.title('Feature Importance Scores')
plt.show()

In [42]:
from sklearn.metrics import mean_squared_error

In [66]:
# FILEPATH: /c:/Users/hamza/Documents/7th Sem/IDM/Challenge2/Multiple Linear Regression.ipynb
# repeat this activity multiple times and record the R2 and MSE for each run
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)
reg2 = LinearRegression().fit(X_train, y_train)
print(reg2.score(X_train, y_train))
print(reg2.coef_)
print(reg2.intercept_)
y_pred_test = reg2.predict(X_test)
mse = mean_squared_error(y_test, y_pred_test)
rmse = np.sqrt(mse)
print("Root Mean squared error: %.2f" % rmse)
#print("Coefficient of determination: %.3f" % r2_score(y_test, y_pred_test))

[[ 1.68597112e+02 -8.52964625e+01  2.07591971e+04 ... -1.73352743e+06
  -7.29972396e+06 -5.26364970e+06]]
[23565773.75454427]
Root Mean squared error: 13825879.19
[[ 1.68597112e+02 -8.52964625e+01  2.07591971e+04 ... -1.73352743e+06
  -7.29972396e+06 -5.26364970e+06]]
[23565773.75454427]
Root Mean squared error: 13825879.19

In [68]:
# FILEPATH: /c:/Users/hamza/Documents/7th Sem/IDM/Challenge2/Multiple Linear Regression.ipynb
# repeat this activity multiple times and record the R2 and MSE for each run
# reg2 = LinearRegression().fit(X,y)
reg_best.fit(X,y)
# print(reg2.score(X_train, y_train))
# print(reg2.coef_)
# print(reg2.intercept_)
# y_pred_test = reg2.predict(X_test)
# mse = mean_squared_error(y_test, y_pred_test)
# rmse = np.sqrt(mse)
# print("Root Mean squared error: %.2f" % rmse)
#print("Coefficient of determination: %.3f" % r2_score(y_test, y_pred_test))

LinearRegression()

In [51]:
#save row id in a dataframe
row_id = test['row ID']
#drop it from test now
test = test.drop(columns=['row ID'])

In [55]:
test.shape

(77789, 2196)

In [56]:
X.shape

(181507, 2196)

In [57]:
#check if columns of test and X are same
X.columns == test.columns

array([ True,  True,  True, ..., False, False, False])

In [60]:
#show columns that are not same in X and test
X.columns[~X.columns.isin(test.columns)]

Index([], dtype='object')

In [70]:
#now predict
# test = test[X.columns] 
# Reorder the columns of test to match the order used during training
price_doc = reg2.predict(test)

In [ ]:
# Create a DataFrame for the predictions
predictions_df = pd.DataFrame(price_doc, columns=['price_doc'])

# Add the record ID from the test data to the predictions DataFrame
predictions_df.insert(0, 'row ID', row_id)

# Save the predictions to a CSV file
predictions_df.to_csv('MLR.csv', index=False)

In [72]:
predictions_df.shape

(77789, 2)